use_frameworks!

target 'TZBase_Example' do
  pod 'TZBase', :path => '../'

  target 'TZBase_Tests' do
    inherit! :search_paths
    #第三方库如果工程大的话最好放在主工程里，放在组件工程的话依赖多的话编译会很慢
#    pod 'JRSwizzle'
#    pod 'Aspects'
  end
end
